server:
  port: 8301
spring:
  #nacos
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.url}:8008
  application:
    name: Authur-Gateway
  boot: #监控相关
    admin:
      client:
        url: http://${authur-monitor-admin}:8401
        username: Authur
        password: ljb

#网管相关
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  cloud:
    gateway:
      routes:
        - id: Authur-Auth
          uri: lb://Authur-Auth
          predicates:
            - Path=/auth/**
          filters:
            - name: Hystrix
              args:
                name: authfallback
                fallbackUri: forward:/fallback/Authur-Auth
        - id: Authur-Server-System
          uri: lb://Authur-Server-System
          predicates:
            - Path=/system/**
          filters:
            - name: Hystrix
              args:
                name: systemfallback
                fallbackUri: forward:/fallback/Authur-Server-System
        - id: Authur-Server-Test
          uri: lb://Authur-Server-Test
          predicates:
            - Path=/test/**
          filters:
            - name: Hystrix
              args:
                name: testfallback
                fallbackUri: forward:/fallback/Authur-Server-Test
      default-filters:
        - StripPrefix=1
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000