server:
  port: 8301
spring:
  application:
    name: Authur-Gateway
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  boot: #监控相关
    admin:
      client:
        url: http://localhost:8401
        username: Authur
        password: ljb
#监控相关
info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

#Eureka相关
eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 30
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://Authur:ljb@localhost:8001/register/eureka/
#网管相关
zuul:
  routes:
    auth:
      path: /auth/**
      serviceId: Authur-Auth
      sensitiveHeaders: "*"
    system:
      path: /system/**
      serviceId: Authur-Server-System
      sensitiveHeaders: "*"
    test:
      path: /test/**
      serviceId: Authur-Server-Test
      sensitiveHeaders: "*"
  retryable: true
  ignored-services: "*"
  ribbon:
    eager-load:
      enabled: true
#请求超时
ribbon:
  ReadTimeout: 3000