server:
  port: 8101

spring:
  application:
    name: Authur-Auth
  redis:
    database: 0
    host: ${redis.url}
    port: 6379
    password: 123456
    lettuce:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000
  datasource:
    dynamic:
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: AuthurHikariCP
      primary: base
      datasource:
        base:
          username: mysql
          password: lijibing123
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://${mysql.url}:3306/authur_cloud_base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8&useSSL=false
  boot: #监控相关
    admin:
      client:
        url: http://${authur-monitor-admin}:8401
        username: Authur
        password: ljb
  #nacos
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.url}:8008
#监控相关
info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

mybatis-plus:
  type-aliases-package: com.example.authur.common.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false
