server:
  port: 8401

spring:
  application:
    name: Authur-Monitor-Admin
  boot:
    admin:
      ui:
        title: ${spring.application.name}
  security:
    user:
      name: Authur
      password: ljb