server:
  port: 8202

spring:
  application:
    name: Authur-Server-Test
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,com.baomidou.dynamic.datasource.spring.boot.autoconfigure.DynamicDataSourceAutoConfiguration
  boot: #监控相关
    admin:
      client:
        url: http://${authur-monitor-admin}:8401
        username: Authur
        password: ljb
  #nacos
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.url}:8008
#监控相关
info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://${authur-gateway}:8301/auth/user
feign:
  hystrix:
    enabled: true #Feign回退生效
hystrix:
  shareSecurityContext: true
